### ISSUE TITLE
Bot integration

### ISSUE THREAD

**Issue by MissHeda** [Coolkid2342/Simple-Discord-Bump-Reminder#1]
Hey there, would it be okay with you if we integrate your code into our bot? It's a self coded / private bot that is only used on our server. We maybe would edit / add some features to this bump code like a channel that displays the time until a bump is ready. Let me know if that would be okay with you. Have a great day. :)

**Comment by Coolkid2342** [comment]
Hi, some things might need to be tweaked since it was originally written for Discord.JS v12 and might be a tad buggy with the latest version but feel free to edit it as you wish. :)

**Comment by MissHeda** [comment]
Thanks :)

**Comment by Coolkid2342** [comment]
No worries.
